# Generated by Django 5.2.6 on 2025-09-25 17:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('targeted_muscle_group', models.CharField(blank=True, max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SessionExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_index', models.PositiveIntegerField(default=1)),
                ('predicted_1rm', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.exercise')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_exercises', to='core.session')),
            ],
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_number', models.PositiveIntegerField()),
                ('weight', models.FloatField()),
                ('reps', models.PositiveIntegerField()),
                ('avg_velocity_set', models.FloatField(blank=True, null=True)),
                ('velocity_loss_pct', models.FloatField(blank=True, null=True)),
                ('stop_reason', models.CharField(blank=True, choices=[('vl_threshold', 'VL threshold'), ('fpi_threshold', 'FPI threshold'), ('failure', 'Failure'), ('completed', 'Completed')], max_length=32)),
                ('session_exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='core.sessionexercise')),
            ],
        ),
        migrations.CreateModel(
            name='Rep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rep_number', models.PositiveIntegerField()),
                ('mean_velocity', models.FloatField(blank=True, null=True)),
                ('peak_velocity', models.FloatField(blank=True, null=True)),
                ('rom_degrees', models.FloatField(blank=True, null=True)),
                ('duration_sec', models.FloatField(blank=True, null=True)),
                ('workout_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rep_entries', to='core.set')),
            ],
        ),
        migrations.CreateModel(
            name='LoadVelocityPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('load', models.FloatField()),
                ('mean_velocity', models.FloatField()),
                ('predicted_1rm_at_time', models.FloatField(blank=True, null=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lvp_points', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'exercise', 'date'], name='core_loadve_user_id_3ef303_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='sessionexercise',
            constraint=models.UniqueConstraint(fields=('session', 'exercise', 'order_index'), name='unique_exercise_order_per_session'),
        ),
        migrations.AddConstraint(
            model_name='set',
            constraint=models.UniqueConstraint(fields=('session_exercise', 'set_number'), name='unique_set_number_per_session_exercise'),
        ),
        migrations.AddConstraint(
            model_name='rep',
            constraint=models.UniqueConstraint(fields=('workout_set', 'rep_number'), name='unique_rep_number_per_set'),
        ),
    ]
