# Generated by Django 5.2.6 on 2025-09-26 20:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercise',
            options={'ordering': ['name', 'id']},
        ),
        migrations.AlterModelOptions(
            name='loadvelocitypoint',
            options={'ordering': ['-date', 'id']},
        ),
        migrations.AlterModelOptions(
            name='rep',
            options={'ordering': ['rep_number', 'id']},
        ),
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['-started_at', 'id']},
        ),
        migrations.AlterModelOptions(
            name='sessionexercise',
            options={'ordering': ['order_index', 'id']},
        ),
        migrations.AlterModelOptions(
            name='set',
            options={'ordering': ['set_number', 'id']},
        ),
        migrations.AddField(
            model_name='loadvelocitypoint',
            name='source_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.session'),
        ),
        migrations.AddField(
            model_name='loadvelocitypoint',
            name='source_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.set'),
        ),
        migrations.AddField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In progress'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='in_progress', max_length=16),
        ),
        migrations.AddField(
            model_name='sessionexercise',
            name='planned_reps_max',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessionexercise',
            name='planned_reps_min',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessionexercise',
            name='planned_sets_max',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessionexercise',
            name='planned_sets_min',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessionexercise',
            name='target_velocity_max',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='sessionexercise',
            name='target_velocity_min',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='sessionexercise',
            name='target_vl_max',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='sessionexercise',
            name='target_vl_min',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='sessionexercise',
            name='target_zone',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='loadvelocitypoint',
            name='load',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='loadvelocitypoint',
            name='mean_velocity',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='loadvelocitypoint',
            name='predicted_1rm_at_time',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='rep',
            name='duration_sec',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='rep',
            name='mean_velocity',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='rep',
            name='peak_velocity',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='rep',
            name='rom_degrees',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='sessionexercise',
            name='predicted_1rm',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='set',
            name='avg_velocity_set',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='set',
            name='reps',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='set',
            name='velocity_loss_pct',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='set',
            name='weight',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddIndex(
            model_name='rep',
            index=models.Index(fields=['workout_set', 'rep_number'], name='core_rep_workout_b65df3_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['user', 'started_at'], name='core_sessio_user_id_762849_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionexercise',
            index=models.Index(fields=['session', 'order_index'], name='core_sessio_session_b74bb7_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionexercise',
            index=models.Index(fields=['exercise'], name='core_sessio_exercis_d8e002_idx'),
        ),
        migrations.AddIndex(
            model_name='set',
            index=models.Index(fields=['session_exercise', 'set_number'], name='core_set_session_db1a56_idx'),
        ),
    ]
