# Generated by Django 5.2.6 on 2025-09-27 10:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_exercise_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionexercise',
            name='completed_sets_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sessionexercise',
            name='last_set_avg_velocity',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='sessionexercise',
            name='last_set_velocity_loss_pct',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='sessionexercise',
            name='last_stop_reason',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='sessionexercise',
            name='target_percent_1rm_max',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='sessionexercise',
            name='target_percent_1rm_min',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='sessionexercise',
            name='total_reps_completed',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
