# Generated by Django 5.2.6 on 2025-09-27 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sessionexercise_completed_sets_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessionexercise',
            name='target_percent_1rm_max',
        ),
        migrations.RemoveField(
            model_name='sessionexercise',
            name='target_percent_1rm_min',
        ),
    ]
