# Generated by Django 5.2.6 on 2025-09-27 11:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_sessionexercise_target_percent_1rm_max_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionexercise',
            name='target_percent_1rm_max',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='sessionexercise',
            name='target_percent_1rm_min',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
